applications:
  # AI
  - name: chatgpt
    macos:
      source: brew

  - name: codex
    macos:
      source: brew

  - name: codex-app
    macos:
      source: brew

  # Communication
  - name: discord
    arch:
      name: dev.vencord.Vesktop
      source: paru
    fedora:
      name: dev.vencord.Vesktop
      source: flatpak
    macos:
      source: brew

  # Data Management
  - name: syncthing
    arch:
      name: syncthing
      source: pacman
    fedora:
      name: syncthing
      source: dnf
    macos:
      name: syncthing
      source: brew

  # Development Tools
  - name: balenaetcher
    macos:
      source: brew
  - name: ghostty
    arch:
      name: ghostty
      source: pacman
    fedora:
      source: dnf
      copr: scottames/ghostty
    macos:
      source: brew
  - name: visual-studio-code
    arch:
      name: visual-studio-code-bin
      source: paru
    fedora:
      source: script
      script_name: install-vscode.sh
      creates: /usr/bin/code
    macos:
      source: brew

  # Gaming
  - name: steam
    arch:
      source: pacman
    fedora:
      source: dnf

  # Password Management
  - name: 1password
    arch:
      source: paru
    fedora:
      source: script
      script_name: install-1password.sh
      creates: /usr/bin/1password
    macos:
      source: brew

  # Productivity
  - name: obsidian
    arch:
      name: md.obsidian.Obsidian
      source: flatpak
    fedora:
      name: md.obsidian.Obsidian
      source: flatpak
    macos:
      source: brew

  # Proton Services
  - name: proton-drive
    macos:
      source: brew
  - name: proton-mail
    arch:
      name: me.proton.Mail
      source: flatpak
    fedora:
      name: me.proton.Mail
      source: flatpak
    macos:
      source: brew

  # Web Browsers
  - name: firefox
    arch:
      name: app.zen_browser.zen
      source: flatpak
    fedora:
      name: app.zen_browser.zen
      source: flatpak
    macos:
      source: brew
